// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
      apiKey: 'AIzaSyC3FXQHW2xDi_W-GyUZWxUnQC3e0So09lk',
      appId: '1:431762843125:web:acad9dae6d44a0365c2cbc',
      messagingSenderId: '431762843125',
      projectId: 'lo-to-derasoft',
      authDomain: 'lo-to-derasoft.firebaseapp.com',
      storageBucket: 'lo-to-derasoft.appspot.com',
      measurementId: 'G-CZRVP4YR1J',
      databaseURL:
          'https://lo-to-derasoft-default-rtdb.asia-southeast1.firebasedatabase.app/');

  static const FirebaseOptions android = FirebaseOptions(
      apiKey: 'AIzaSyDkNsWJZhb_g1Ew5RJUnCh-a6oWH2z-5vI',
      appId: '1:431762843125:android:4ce50110832ff0dd5c2cbc',
      messagingSenderId: '431762843125',
      projectId: 'lo-to-derasoft',
      storageBucket: 'lo-to-derasoft.appspot.com',
      databaseURL:
          'https://lo-to-derasoft-default-rtdb.asia-southeast1.firebasedatabase.app/');

  static const FirebaseOptions ios = FirebaseOptions(
      apiKey: 'AIzaSyDyaAVHzMmEM9lDrmxQwUvwkWGc-UecC7c',
      appId: '1:431762843125:ios:c5471c0468a72f495c2cbc',
      messagingSenderId: '431762843125',
      projectId: 'lo-to-derasoft',
      storageBucket: 'lo-to-derasoft.appspot.com',
      iosBundleId: 'com.example.appBlocFlutter',
      databaseURL:
          'https://lo-to-derasoft-default-rtdb.asia-southeast1.firebasedatabase.app/');

  static const FirebaseOptions macos = FirebaseOptions(
      apiKey: 'AIzaSyDyaAVHzMmEM9lDrmxQwUvwkWGc-UecC7c',
      appId: '1:431762843125:ios:9fc97ac89c3465795c2cbc',
      messagingSenderId: '431762843125',
      projectId: 'lo-to-derasoft',
      storageBucket: 'lo-to-derasoft.appspot.com',
      iosBundleId: 'com.example.appBlocFlutter.RunnerTests',
      databaseURL:
          'https://lo-to-derasoft-default-rtdb.asia-southeast1.firebasedatabase.app/');
}
